/**
 * Return a new array with unique items based on the key generated by `getKey` function.
 */
export function getUniqueArrayByKey<T>(
	array: T[],
	getKey: (t: T) => string,
): T[] {
	const seen = new Set<string>();
	return array.filter((item) => {
		const key = getKey(item);
		if (seen.has(key)) return false;
		seen.add(key);
		return true;
	});
}
